require("../../WebModule/lib/Reflection.js");
require("../../WebModule/lib/Console.js");
require("../../WebModule/lib/Valid.js");
require("../../WebModule/lib/Help.js");
require("../../WebModule/lib/Task.js");
require("../../WebModule/lib/Test.js");
require("../lib/PageVisibilityEvent.js");
require("../release/PageVisibilityEvent.min.js");
require("./testcase.js");
